In [2]:
import numpy as np
import gym
import random

In [3]:
env=gym.make("FrozenLake-v0")
env.render()


SFFF
FHFH
FFFH
HFFG


In [4]:
action_size=env.action_space.n
state_size=env.observation_space.n

In [5]:
qtable=np.zeros((state_size,action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
total_episodes=15000
learning_rate=0.8
max_steps=99
gamma=0.95

epsilon=1.0
max_epsilon=1.0
min_epsilon=0.01
decay_rate=0.005

In [8]:
rewards=[]

for episode in range(total_episodes):
    state=env.reset()
    step=0
    done=False
    total_rewards=0
    
    for step in range(max_steps):
        exp_exp_tradeoff=random.uniform(0,1)
        
        if exp_exp_tradeoff>epsilon:
            action=np.argmax(qtable[state,:])
        
        else:
            action=env.action_space.sample()
            
        new_state,reward,done,info=env.step(action)
        
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards+=reward
        
        state=new_state
        
        if done==True:
            break
            
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)
    
print("Score over time: "+str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.4845333333333333
[[2.56645151e-01 8.16957428e-02 5.26924733e-02 5.31675625e-02]
 [4.83421059e-03 5.34318502e-03 4.73291734e-04 1.96985277e-01]
 [3.16969247e-03 4.84797957e-02 4.80729287e-03 1.42016744e-02]
 [3.34354898e-03 3.05509069e-03 1.51676242e-03 1.01439937e-01]
 [4.17103673e-01 3.79720499e-02 3.80679431e-04 3.76419679e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.92196795e-07 1.05546770e-06 3.31276242e-02 1.00920178e-08]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.44590794e-02 1.47500590e-02 1.92785076e-01 7.08188759e-01]
 [2.87980542e-02 5.92127874e-01 2.14138232e-02 4.55905221e-02]
 [2.44889966e-01 7.53036974e-04 6.68634396e-03 2.29567705e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.15445938e-01 9.94149278e-03 6.72666015e-01 8.22502541e-03]
 [3.65412549e-01 9.47468020e-01 1.11649940e-01 2.23801996e-01]
 [0.00000000e+00 0.

In [10]:
env.reset()

for episode in range(5):
    state=env.reset()
    step=0
    done=False
    print("************************************")
    print("EPISODE",episode)
    
    for step in range(max_steps):
        
        action=np.argmax(qtable[state,:])
        
        new_state,reward,done,info=env.step(action)
        
        if done:
            
            env.render()
            
            print("Number of steps",step)
            break
        state=new_state
env.close()

************************************
EPISODE 0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 12
************************************
EPISODE 1
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 55
************************************
EPISODE 2
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 7
************************************
EPISODE 3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 50
************************************
EPISODE 4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 22
