In [9]:
import numpy as np
import gym
import random

In [17]:
from gym.envs.registration import register
register(
    id="FrozenLakeNotSlippery-v0",
    entry_point="gym.envs.toy_text:FrozenLakeEnv",
    kwargs={"map_name":"4x4","is_slippery":False},
    max_episode_steps=100,
    reward_threshold=0.8196,
)

In [18]:
env=gym.make("FrozenLakeNotSlippery-v0")
env.render()


SFFF
FHFH
FFFH
HFFG


In [22]:
action_size=env.action_space.n
state_size=env.observation_space.n

In [23]:
qtable=np.zeros((state_size,action_size))

In [24]:
total_episodes=20000
max_steps=99

learning_rate=0.8
gamma=0.618

epsilon=1.0
max_epsilon=1.0
min_epsilon=0.01
decay_rate=0.001

In [25]:
rewards=[]

for episode in range(total_episodes):
    state=env.reset()
    step=0
    done=False
    total_rewards=0
    
    for step in range(max_steps):
        exp_exp_tradeoff=random.uniform(0,1)
        
        if exp_exp_tradeoff>epsilon:
            action=np.argmax(qtable[state,:])
        
        else:
            action=env.action_space.sample()
        
        new_state,reward,done,info=env.step(action)
        
        qtable[state,action]=qtable[state,action]+learning_rate*(reward+gamma*np.max(qtable[new_state,:])-qtable[state,action])
        
        total_rewards+=reward
        
        state=new_state
        
        if done==True:
            break
            
    epsilon=min_epsilon+(max_epsilon-min_epsilon)*np.exp(-decay_rate*episode)   
    rewards.append(total_rewards)

print("Score over time: "+str(sum(rewards)/total_episodes))
print(qtable)
print(epsilon)

Score over time: 0.9342
[[0.0557097  0.09014515 0.09014515 0.0557097 ]
 [0.0557097  0.         0.14586594 0.09014515]
 [0.09014515 0.23602903 0.09014515 0.14586594]
 [0.14586594 0.         0.09014514 0.09014398]
 [0.09014515 0.14586594 0.         0.0557097 ]
 [0.         0.         0.         0.        ]
 [0.         0.381924   0.         0.14586594]
 [0.         0.         0.         0.        ]
 [0.14586594 0.         0.23602903 0.09014515]
 [0.14586594 0.381924   0.381924   0.        ]
 [0.23602903 0.618      0.         0.23602903]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.381924   0.618      0.23602903]
 [0.381924   0.618      1.         0.381924  ]
 [0.         0.         0.         0.        ]]
0.01000000204258365


In [26]:
env.reset()
env.render()
print(np.argmax(qtable,axis=1).reshape(4,4))


SFFF
FHFH
FFFH
HFFG
[[1 2 1 0]
 [1 0 1 0]
 [2 1 1 0]
 [0 2 2 0]]


In [28]:
env.reset()
rewards=[]

for episode in range(5):
    state=env.reset()
    step=0
    done=False
    print("********************************************")
    print("EPISODE",episode)
    
    for step in range(max_steps):
        env.render()
        action=np.argmax(qtable[state,:])
        
        new_state,reward,done,info=env.step(action)
        
        if done:
            break
        state=new_state
env.close()

********************************************
EPISODE 0

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
********************************************
EPISODE 1

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
********************************************
EPISODE 2

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
********************************************
EPISODE 3

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
********************************************
EPISODE 4

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (